spring:
  data:
    mongodb:
      uri: mongodb://admin:admin@localhost:27017/todosdb?authSource=admin
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8180/realms/todo-project-realm
actuator:
  username: admin
  password: admin

springdoc:
  swagger-ui:
    oauth:
      client-id: "todo-project-client"
      use-pkce-with-authorization-code-grant: true
    oauth2-redirect-url: "http://localhost:8082/swagger-ui/oauth2-redirect.html"