spring:
  application:
    name: todo-app
server:
  port: 8082
logging:
  level:
    org.springframework.security: DEBUG
    org.springframework.security.oauth2: DEBUG
    com.example.todoapp.aop: INFO
management:
  endpoints:
    web:
      exposure:
        include: info,health
actuator:
  username: ${ACTUATOR_USERNAME:admin}
  password: ${ACTUATOR_USERNAME:admin}