spring:
  application:
    name: todo-app
server:
  port: ${PORT:8080}
  servlet:
    context-path: /api
logging:
  level:
    org.springframework.security: DEBUG
    org.springframework.security.oauth2: DEBUG
    com.example.todoapp.aop: INFO
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics