spring:
  data:
    mongodb:
      uri: ${SPRING_DATA_MONGODB_URI}
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://keycloak.michaelgoldman.dev/realms/todo-project-realm
management:
  server:
    port: ${PORT:0}
    address: 0.0.0.
  endpoints:
    web:
      exposure:
        include: health,info,metrics
actuator:
  username: ${ACTUATOR_USERNAME}
  password: ${ACTUATOR_PASSWORD}