spring:
  data:
    mongodb:
      uri: ${SPRING_DATA_MONGODB_URI}
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://keycloak.michaelgoldman.dev/realms/todo-project-realm
actuator:
  username: ${ACTUATOR_USERNAME}
  password: ${ACTUATOR_PASSWORD}

springdoc:
  swagger-ui:
    oauth:
      client-id: "todo-project-client"
      use-pkce-with-authorization-code-grant: true
    oauth2-redirect-url: "https://todo-backend-w132.onrender.com/swagger-ui/oauth2-redirect.html"