spring:
  application:
    name: todo-app
server:
  port: 8082
  servlet:
    context-path: /api
logging:
  level:
    org.springframework.security: DEBUG
    org.springframework.security.oauth2: DEBUG
    com.example.todoapp.aop: INFO
management:
  server:
    port: 9090


    spring:
      web:
        mvc:
          servlet:
            path=/api: