spring:
  data:
    mongodb:
      uri: mongodb://admin:admin@localhost:27017/todosdb?authSource=admin
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8180/realms/todo-project-realm
management:
  server:
    address: 127.0.0.1
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
actuator:
  username: admin
  password: admin
