name: Build & Test Backend

on: 
  push:
    paths: [backend/**]
  pull_request:
    paths: [backend/**]
  workflow_dispatch:

jobs:
  build-test:
    runs-on: ubuntu-latest
    
    env:
      SPRING_PROFILES_ACTIVE: ci

    defaults:
      run:
        working-directory: backend
    
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-java@v4
        with: 
          java-version: '17'
          distribution: 'temurin'
          cache: 'maven'

      - name: Build & test backend
        run: mvn -B -ntp clean verify
        
