name: First Workflow
on: workflow_dispatch
jobs:
  first-job:
    runs-on: ${{matrix.os}}
    strategy:
      matrix: 
        os: [ubuntu-latest, windows-latest, macOS-latest]
        
    steps: 
      - name: Print greeting
        run: echo "Hello world!"
      - name: Pring random stuff
        run: |
            echo "First random line"
            echo "Second random line"
      - name: Print goodbye
        run: echo "Done - Bye!"
