name: Test Backend

on: 
  push:
    paths:
      - 'backend/**'
  pull_request:
    paths: [backend/**]

jobs:
  - build-test:
    runs-on: ${{ matrix.o }}
    strategy:
      matrix: 
        os: [ubuntu-latest, windows-latest, macos-latest]

    defaults:
      run:
        working-directory: backend
    
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-java@v4

        with: 
          java-version: '17'
          distribution: 'temurin'
          cache: 'maven'

      - name: Build & test backend
        run: mvn -B -ntp clean verify
        